pipeline {
    agent any
    tools { 
        maven 'maven-3.5.0'
        jdk 'jdk1.8.0_144' 
    }
    stages {
        stage ('Initialize') {
            steps {
                bat '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }
        
        stage('compile') {
		      steps {
		        bat 'mvn clean install'
		      }
		 }

        stage ('Build') {
            steps {
               bat 'cd task-mgr-svc && mvn package docker:build'
            }
        }
    }
}
